### ISSUE TITLE
"Zombie" Games and Lobby not Correctly Updating (Copy and Paste)

### ISSUE THREAD

**Issue by MGLFlex** [andre-jar/Stick-Arena-Private-Server#1]
Resending message here to make it easier for you hopefully.

Stick Arena Private Server is running pretty swell. We even got FAC to work by changing the local IP to the IP of the server host. However, couple pretty game breaking issues.

When a host leaves a custom game, the game they created is not properly deregistering in the server (probably issue with communication between client and server). This usually happens when a host leaves their game while other players are also in the same game. It also does not always correctly kick out the other players who joined. This leaves the game active for upwards of days to even weeks, with no one actually inside the game. But when joined, the host will be in the top left corner, invulnerable to any attacks. If left up for long periods of time, it can cause the servers to lag and even at times crash.
Not all online players are visible in lobby to everyone. For some reason, only the person who most recently logged in can accurately see everyone who is currently online (also probably a communication issue). This means that even if there are 2 people in the same server, it shows one person that they're the only user online, meaning that you can't even see what the other player is typing because they aren't appearing as "online" on your screen.
When a game is created, the first one will start at 5:00, but subsequent games will start at 4:30. I suspect this is due to the fact that in the original game, there was a system in place that would offset each game to start 30 seconds later in order for the post game stat board to show for 30 seconds, however private server doesn't have this so if you join when a game is in the post game stats, you will join the map and be able to move, but you can't hit anyone who is in the credits screen.
Any help would be greatly appreciated.

**Comment by andre-jar** [comment]
I was able to replicate all of the mentioned issues in my test environment. I will try to fix them during the next weekend. Stay tuned for updates.

**Comment by andre-jar** [comment]
I just want to give you a little update:
* I fixed the bug with the wrong starting times. It should be 5 minutes every round now. Also players joining in between matches get teleported to the scoreboard. The issue was that the game uses a negative round time to detect the time where the scoreboard is displayed. The old code from the original project did not account for that.
* I fixed the bug with users not getting properly kicked out of the game in a vip or custom map game now. Apparently I made a mistake because deregistering players modifies the list I was iterating over at the same time (like a concurrent modification basically). The only drawback is that after getting kicked all the players other than the creator of the game can see some "ghost" like players in the lobby now(blank users with no data). It is not a game breaking bug, just a slight inconvenience. This bug might be linked to the lobby not getting updated properly. I will take care of that later when everything else works like it should.

Unfortunately I have not been able to fix the bug with the player visibility in the lobby until now. I'm still investigating the issue. It seems to be only happening after the initial start of the flash client. If you login again or play a few matches it starts getting updated properly. I will continue to investigate the issue.

**Comment by andre-jar** [comment]
I was finally able to fix the bug with the incorrect lobby display now. It should be displayed correctly now. The issue was that the client opens 2 connections:
* One connection to receive the policy file
* After the policy file has been received the first connection is closed by the client and another connection for the main game is opened

The server code accidentally handled the first closed connection as a disconnected player and thus creates an incorrect state in the clients. This also explains why only newly started clients have that problem, because the policy file is only received once per started client.

There are two additional bugs that I'm currently looking into (the bug after killroom/vip/custom game kick and the win logic seems to be a bit off by letting players both win if they have a different death number and equal number of kills), but this particular bug should be fixed now.

Can you test the fixes and let me know if everything works now?

**Comment by MGLFlex** [comment]
Hey Andre,

I appreciate the commitment to helping us better the servers. It's very nice of you to help us out like this. Unfortunately, when we tried testing the games on the live servers, we couldn't test if games are properly deregistering because there was another known bug (not as common before) now occurring every game. The bug is that when you create a game that starts at 5:00, after 15 seconds or at about 4:44, the timer resets back to 5:00 and infinitely loops, meaning the game never ends. This effectively turns the game into a "zombie" game with a "zombie host", because leaving the custom game as a host doesn't do anything, and when you join the game back on the same account, there will be two of you. We have not seen any other bugs, but this was while we were trying to play the game, and unfortunately couldn't so we had to roll back the changes for now. Can you please add my discord so we can have an easier time communicating? My username is "xefl". Thank you so much again for the help and continued support of the stick arena private server, we appreciate everything you have done and are doing for our small community.

**Comment by andre-jar** [comment]
I have sent a request on discord. I have not been able to replicate this with the given information.

**Comment by andre-jar** [comment]
@MGLFlex Can I close this issue now or do you still experience problems? You can always create a new one if it is required.
